# Info about you
name: David Do
position: Computer Science
email: dungdo.hust@gmail.com
company_name: Visionin - Octan Network
company_url: https://vision-in.co.kr/
place_name: Seoul, SK

# Blog info
title: Do's Blog
description: Blog
url: https://csdaviddo.github.io/
main_github_io: true
long_description: >-
    Hi!  Welcome to my blog site.  My name is David Do, and I am a Senior Deep Learning Engineer at Visionin. 
    My research and engineering interests are mainly in the areas of artificial intelligence, blockchain,
    general computer science, and user-friendly software engineering.

# Social links
github_url: https://github.com/dungdo123
linkedin_url: https://www.linkedin.com/in/dungdo398/
social:
  links:
    - https://www.linkedin.com/in/dungdo398/
    - https://github.com/dungdo123

# Images + files
logo: assets/img/snow_avt.png
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: light  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38
